version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord_bot
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
